channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pip=20.2
  - cudatoolkit=10.1
  - pytorch=1.7.1=py3.6_cuda10.1.243_cudnn7.6.3_0
  - torchvision=0.8.2=py36_cu101
  - torchtext=0.8.1=py36
  - opencv=3.4
  - matplotlib=2.2
  - pandas=1.1
  - numpy=1.19