channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip=20.2
  - cudatoolkit=10.1
  - jupyterlab=3.0
  - pytorch=1.7.0=py3.7_cuda10.1.243_cudnn7.6.3_0
  - torchvision=0.8.1=py37_cu101
  - opencv=4.5.1
  - matplotlib=2.2.3
  - pandas=1.2.3
  - numpy=1.20.2