channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip=20.2
  - pytorch=1.7.1=py3.7_0
  - torchvision=0.8.2=py37_cpu
  - torchtext=0.8.1
  - opencv=3.4
  - matplotlib=2.2
  - pandas=1.1
  - numpy=1.19